import { all } from "axios";

export const apiUrls = {
    homepage: 'Home',
    section: 'Section',
    contact: 'Contact',
    registerCustomer: 'Register',
    verifyCustomerEmail: 'VerifyEmail',
    loginCustomer: 'Customer/Login',
    loginWithApple: 'Customer/LoginWithApple',
    customerInfo: 'Info',
    changeCustomerPassword: 'ChangePassword',
    updateCustomerInfo: 'UpdateCustomerInfo',
    addCustomerAddress: 'AddAddress',
    updateCustomerAddress: 'UpdateAddress',
    setDefaultCustomerAddress: 'SetDefaultAddress',
    deleteCustomerAddress: 'DeleteAddress',
    getCustomerAddress: 'Address',
    initiatePasswordReset: 'InitiatePasswordReset',
    resendVerificationEmail: 'ResendVerification',
    resetPassword: 'ResetPassword',
    submitContact: 'SubmitContact',
    subjects: 'Subjects',
    faqs: 'Faqs',
    product: 'Product',
    allProductsByCategory: 'AllProductsByCategory',
    categories: 'Categories',
    details: 'Details',
    dates: 'Dates',
};