export const routeUrls = {
    home: '/',
    about: '/about',
    comingSoon: '/coming-soon',
    register: '/auth/register',
    login: '/auth/login',
    emailVerify: '/email/verify',
    emailVerified: '/email/verified',
    myAccount: '/customer/my-account',
    forgotPassword: '/auth/forgot-password',
    changePassword: '/auth/change-password',
    contactUs: '/contact-us',
    faqs: '/faqs/:typeId/:typeName',
    shop: '/shop',
    ourDates: '/our-dates',
    productDetails: '/product/:productId/:productName',
    DatesDetails: '/dates/:datesId/:datesName',
};