export const RouterUrls = {
    productsList: '/products',
    productAdd: '/products/add',
    productEdit: '/products/edit/:id',
    datesList: '/dates',
    dateAdd: '/dates/add',
    dateEdit: '/dates/edit/:id',
    customersList: '/customers',
    addressesList: '/addresses',
    ordersList: '/orders',
    transactionsList: '/transactions',
    datesGallery: '/dates/gallery/:dateId',
    productsGallery: '/products/gallery/:prdId',
    galleryProductAdd: '/products/gallery/add',
    galleryDateAdd: '/dates/gallery/add',
    collectionsList: '/collections',
    collectionAdd: '/collections/add',
    collectionEdit: '/collections/edit/:id',

};
