export const RouterUrls = {
    productsList: '/products',
    productAdd: '/products/add',
    productEdit: '/products/edit/:id',
    datesList: '/dates',
    dateAdd: '/dates/add',
    dateEdit: '/dates/edit/:id',
    customersList: '/customers',
    addressesList: '/addresses/:customerId/:title',
    ordersList: '/orders',
    transactionsList: '/transactions',
    datesGallery: '/dates/gallery/:dateId/:title',
    productsGallery: '/products/gallery/:prdId/:title',
    galleryProductAdd: '/products/gallery/add',
    galleryDateAdd: '/dates/gallery/add',
    collectionsList: '/collections',
    collectionAdd: '/collections/add',
    collectionEdit: '/collections/edit/:id',
    sectionsList: '/sections',
    sectionAdd: '/sections/add',
    sectionEdit: '/sections/edit/:id',
    faqsList: '/faqs',
    faqAdd: '/faqs/add',
    faqEdit: '/faqs/edit/:id',
    contactsList: '/contacts'
};
